"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

import itertools
from collections import deque

def fib():
    """
    Each term is the sum of the last two
    >>> list(itertools.islice(fib(), 10))
    [1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
    """
    d = deque([1], maxlen=2)
    while True:
        d.append(sum(d))
        yield d[-1]


